version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    build:
      context: ./requirements/nginx/
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        CERT_UID: ${CERT_UID}
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress/
    env_file: .env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    expose:
      - "9000"
    restart: on-failure

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb/
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"
    restart: on-failure

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: "${VOLUMES_PATH}/wordpress"
  
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: "${VOLUMES_PATH}/mariadb"

networks:
  inception:
    driver: bridge
