version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    build:
      context: ./requirements/nginx/
      args:
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        CITY: ${CITY}
        ORG: ${ORG}
        ORG_UNIT: ${ORG_UNIT}
        DOMAIN_NAME: ${DOMAIN_NAME}
        CERT_UID: ${CERT_UID}
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress/
    env_file: .env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    expose:
      - "9000"
    restart: on-failure

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb/
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"
    restart: on-failure

  adminer:
    container_name: adminer
    image: adminer
    build: ./requirements/adminer/
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
      - "8080:80"
    restart: on-failure

  redis:
    container_name: redis
    image: redis
    build: ./requirements/redis/
    networks:
      - inception
    expose:
      - "6379"
    restart: on-failure

  ftp:
    container_name: ftp
    image: ftp
    build:
      context: ./requirements/ftp/
      args:
        FTP_USER: ${FTP_USER}
        FTP_PSSWD: ${FTP_PSSWD}
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    ports:
      - "20:20"
      - "21:21"
      - "42100-42105:42100-42105" 
    env_file:
      - .env
    restart: on-failure

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: "${VOLUMES_PATH}/wordpress"
  
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: "${VOLUMES_PATH}/mariadb"

networks:
  inception:
    driver: bridge
